# this is a copy of the dependencies listed in the gemspec,
# since bundix doesn't support reading the gemspec itself.
source 'https://rubygems.org'

gem 'activerecord', '~> 6.0'
gem 'ruby-progressbar'

group :development do
  gem 'rake', '~> 12.3'
  gem 'rspec', '~> 3.8'
  gem 'temping', '~> 4.0'
  gem 'byebug'
  gem 'sqlite3', '~> 1.4'
  gem 'yard'
  gem 'reek'
end
