# this is a copy of the dependencies listed in the gemspec,
# since bundix doesn't support reading the gemspec itself.
source 'https://rubygems.org'

gem 'activerecord', '~> 5.2'
gem 'ruby-progressbar'

group :development do
  gem 'rake', '~> 12.3'
  gem 'rspec', '~> 3.8'
  gem 'temping', '~> 3.10'
  gem 'byebug'
  gem 'sqlite3', '~> 1.3.10'
  gem 'mysql2'
  gem 'pg'
  gem 'yard'
  gem 'reek'
end
