language: ruby
rvm:
  - 3.1.4
cache: bundler
before_install:
  - gem update --system
  - gem update bundler
services:
  - mysql
env:
  - DB=sqlite
  - DB=mysql
before_script:
  bundle exec rake db:create

gemfile:
  - gemfiles/activerecord_6.0.gemfile
