language: ruby
rvm:
  - 2.5.3
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
services:
  - mysql
env:
  - DB=sqlite
  - DB=mysql
before_script:
  bundle exec rake db:create

gemfile:
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_6.0.gemfile
